### ISSUE TITLE
Advanced Obstacle Avoidance

### ISSUE THREAD

**Issue by alex-nordin** [DIT112-V21/group-08#12]
_As a Driver I want the car to be partially autonomous, so that I have the option to not always control it manually_

Acceptance criteria:
- The car shall be able to continue its journey around the environment even if it finds an obstacle. 
- The car should choose the path with the most space to it’s left or right if it encounters an obstacle

**Comment by adamtelles** [comment]
Issue resolved in Advanced Obstacle Avoidance branch. May not need to be merged.
