### ISSUE TITLE
Advanced Voice Recognition

### ISSUE THREAD

**Issue by NiklasHoglund** [DIT112-V21/group-08#41]
**User Story**
- As a driver I want the car to respond to synonyms of a word via interface and interpret sentences so that I don't have to know the exact command lines to drive the car.

**Acceptance criteria:**
- The car should be able to be controlled with voice control using different words or sentences but with the same meaning. 
- The car should still have the same response time when using synonyms as the exact commands provided in the instructions of the car.
- The interpreted sentences should still have the same meaning when synonyms are used.

**Comment by AhmedYasser-gu** [comment]
We are trying to get response time lower, by reducing the method timeout after the " user " command.

**Comment by AhmedYasser-gu** [comment]
Covered with Dialog flow fixes
